Import('qc_env', 'common', 'messaging')

# evaluators_src = [
#   "evaluators/can_valid_evaluator.cpp",
#   "evaluators/car_recognized_evaluator.cpp",
#   "evaluators/car_speed_evaluator.cpp",
#   "evaluators/const_evaluator.cpp",
#   "evaluators/resource_evaluator.cpp",
#   "evaluators/calibrated_evaluator.cpp",
#   "evaluators/posenet_evaluator.cpp"
# ]


src = ["main.cpp", "shott.cpp"]  # + evaluators_src
shott_objs = qc_env.Object(src)
qc_env.Program("shott", shott_objs, LIBS=[common, messaging, 'zmq'], CPPPATH=["libs/cereal-1.3.2"])
