import os
import subprocess
Import('env', 'common', 'messaging', 'arch')

# Qt build environment
qt_env = env.Clone()
qt_modules = ["Core", "DBus"]

qt_libs = []
if arch == "Darwin":
    qt_env['QTDIR'] = f"{brew_prefix}/opt/qt@5"
    qt_dirs = [
        os.path.join(qt_env['QTDIR'], "include"),
    ]
    qt_dirs += [f"{qt_env['QTDIR']}/include/Qt{m}" for m in qt_modules]
    qt_env["LINKFLAGS"] += ["-F" + os.path.join(qt_env['QTDIR'], "lib")]
    qt_env["FRAMEWORKS"] += [f"Qt{m}" for m in qt_modules] + ["OpenGL"]
    qt_env.AppendENVPath('PATH', os.path.join(qt_env['QTDIR'], "bin"))
else:
    qt_install_prefix = subprocess.check_output(
        ['qmake', '-query', 'QT_INSTALL_PREFIX'], encoding='utf8').strip()
    qt_install_headers = subprocess.check_output(
        ['qmake', '-query', 'QT_INSTALL_HEADERS'], encoding='utf8').strip()

    qt_env['QTDIR'] = qt_install_prefix
    qt_dirs = [
        f"{qt_install_headers}",
    ]

    qt_gui_path = os.path.join(qt_install_headers, "QtGui")
    qt_gui_dirs = [d for d in os.listdir(
        qt_gui_path) if os.path.isdir(os.path.join(qt_gui_path, d))]
    qt_dirs += (
        [
            f"{qt_install_headers}/QtGui/{qt_gui_dirs[0]}/QtGui",
        ]
        if qt_gui_dirs
        else []
    )
    qt_dirs += [f"{qt_install_headers}/Qt{m}" for m in qt_modules]

    qt_libs = [f"Qt5{m}" for m in qt_modules]

qt_env['QT3DIR'] = qt_env['QTDIR']


# compatibility for older SCons versions
try:
    qt_env.Tool('qt3')
except SCons.Errors.UserError:
    qt_env.Tool('qt')

qt_env['CPPPATH'] += qt_dirs
qt_env['CPPPATH'] += ["#third_party/json11", "libs/cereal-1.3.2"]

qt_flags = [
    "-D_REENTRANT",
    "-DQT_NO_DEBUG",
    "-DQT_CORE_LIB",
    "-DQT_MESSAGELOGCONTEXT",
]
qt_env['CXXFLAGS'] += qt_flags
qt_env['LIBPATH'] += []
qt_env['LIBS'] = qt_libs + ["common", "zmq", "json11", messaging]

if GetOption("clazy"):
    checks = [
        "level0",
        "level1",
        "no-range-loop",
        "no-non-pod-global-static",
    ]
    qt_env['CXX'] = 'clazy'
    qt_env['ENV']['CLAZY_IGNORE_DIRS'] = qt_dirs[0]
    qt_env['ENV']['CLAZY_CHECKS'] = ','.join(checks)


# qt.Library("shott", ["main.cpp", "network.cpp"])

shott_srcs = ["main.cpp", "network.cpp", "shott.cpp"]
shott_objs = qt_env.Object(shott_srcs)
qt_env.Program("shott", shott_objs)
