Import('env', 'common', 'messaging')

env["CPPPATH"] += ["libs/cereal-1.3.2"]
shott_srcs = ["main.cpp", "shott.cpp"]
shott_objs = env.Object(shott_srcs)
env.Program("shott", shott_objs, LIBS=[common, messaging, 'zmq'])
