import subprocess

Import('env', 'common', 'messaging')

dbus_headers = subprocess.check_output(['pkg-config', 'dbus-1', '--cflags'], encoding='utf8').strip().split()

env["CXXFLAGS"] += [dbus_headers]
env["CPPPATH"] += ["libs/cereal-1.3.2"]
shott_srcs = ["main.cpp", "network_state.cpp", "dispenser.cpp"]
shott_objs = env.Object(shott_srcs)
env.Program("shott", shott_objs, LIBS=[common, messaging, 'zmq', 'dbus-1'])
